In [4]:
import numpy as np

a = np.random.randn(5)


In [5]:
print(a)

[ 0.52936435  1.29005742  1.24113483 -0.20129285 -0.11791545]


In [8]:
print(a.shape)

(5,)


In [12]:
print(a.T)

[ 0.52936435  1.29005742  1.24113483 -0.20129285 -0.11791545]


In [13]:
print(np.dot(a, a.T))

3.53931330036055


In [14]:
a = np.random.randn(5,1)

print(a)

[[-1.17955463]
 [-0.33119002]
 [ 1.0968009 ]
 [-1.98117632]
 [-0.39931278]]


In [15]:
print(a.T)

[[-1.17955463 -0.33119002  1.0968009  -1.98117632 -0.39931278]]
