In [3]:
import numpy as np
a = np.random.randn(5)

print(a)

[-2.02343638 -0.8199994   0.02656768  1.23319234  0.9176036 ]


In [6]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 0.0, 53.2],
             [1.9, 0.3, 0.12, 99.0]])

print(A)

[[ 56.     0.     4.4   68.  ]
 [  1.2  104.     0.    53.2 ]
 [  1.9    0.3    0.12  99.  ]]


In [7]:
cal = A.sum(axis=0)
print(cal)

[ 59.1  104.3    4.52 220.2 ]


In [10]:
percentage = 100 * A / cal.reshape(1, 4)
print(percentage)

[[94.75465313  0.         97.34513274 30.88101726]
 [ 2.03045685 99.71236817  0.         24.15985468]
 [ 3.21489002  0.28763183  2.65486726 44.95912807]]
